### ISSUE TITLE
ERR_CONNECTION_REFUSED Post Install

### ISSUE THREAD

**Issue by SDpyro** [pdulvp/jellyfin-qnap#121]
+1 with this issue
nas.local refused to connect.
ERR_CONNECTION_REFUSED

Model: TVS-761
I rechecked after an hour just in case there was some housekeeping needed in the background.

**Comment by pdulvp** [comment]
> what port are you using? 8920 (https) or 8096 (http)?
> 
> I just checked and the shortcut on my qnap automatically tries https now and fails with connection refused, because https is not automatically active on jellyfin server, so the reaction is normal.
> if thats the case for you too, try http

oh, didnt notice that. will try to see if possible to make it fixed

**Comment by SDpyro** [comment]
I used the link from the app on the QNAP app section:
http://nas.local:8920/web/
For thoroughness I checked
https://nas.local:8920/web/
http://nas.local:8920/web/
https://nas.local:8920/web/

**Comment by Oednerich** [comment]
you have to use http with 8096, like  http://nas.local:8096

**Comment by pdulvp** [comment]
FYI, 
If you connect to the NAS using http (8080), button on jellyfin "open" will open http
If you connect to the NAS using https, it will open the https even if the https is not enabled/configured in jellyfin.

**Comment by yahyavi** [comment]
Have a similar problem. Fresh install on TS464. Did the initial setup by manually going to nas:8096 (setup admin/password) and 1 folder.  Cannot connect anymore. From my understanding there should be a config to allow remote access but I cannot login to the admin page. How to fix that?

<img width="1194" alt="image" src="https://github.com/user-attachments/assets/8ea8a66d-20fa-4e9d-8b4e-b37da0eed4ae">

**Comment by pdulvp** [comment]
> Have a similar problem. Fresh install on TS464. Did the initial setup by manually going to nas:8096 (setup admin/password) and 1 folder.  Cannot connect anymore. From my understanding there should be a config to allow remote access but I cannot login to the admin page. How to fix that?
> 
> <img width="1194" alt="image" src="https://github.com/user-attachments/assets/8ea8a66d-20fa-4e9d-8b4e-b37da0eed4ae">
> 

and even if you reopen the root page?
http://192.168.1.50:8096/web/ (sometimes sub pages fails but the root make it work?)

did you configure more stuff in jellyfin (like https?)

in the nas installation folder (something like /share/CACHEDEV1_DATA/.qpkg/jellyfin) there shall have a log folder with hopefully more info to dig up)

**Comment by SDpyro** [comment]
I'm tied up until Monday, I'll get back to you by the afternoon pacific
time with as much data as I can provide.
Thank you so much for all your help!

**Comment by yahyavi** [comment]
So I got the email about your comments and clicked on my phone on the link @pdulvp posted and in iphone safari it loaded and I was able to login. Then I tried again on my desktop chrome and still kept getting the same error with refreshes, etc. 

I decided to clean the site data in chrome and refreshed and that forced another login and it started working. 
I guess, for whatever reason the cookie that was getting set during the initial setup was breaking something. 

<img width="421" alt="image" src="https://github.com/user-attachments/assets/16495a18-22cd-43da-b7ec-10b64ec5be03">

Thanks for the help.

**Comment by OutOfThisPlanet** [comment]
I also have this issue (TS-253A).

Installed over the top of an existing jellyfin, and I can't connect. 
Logs seem to show that the server is running in the background.

Will dig into it more.

**Comment by OutOfThisPlanet** [comment]
I ended up uninstalling the original jellyfin app on QNAP, and installed the new one. 
Works fine after this. 
Now transferring the backups back to the server.

Seems that this jellyfin opkg cannot be installed over the top of a jellyfin install that came from somewhere else.

**Comment by OutOfThisPlanet** [comment]
After copying over the backup files, it no longer works. 

Fun times.

**Comment by OutOfThisPlanet** [comment]
Rebuilt it, and did some config, added some plugins, and restarted the server.

It never came back online. 

I SSH'd into the box to start the server....

`[oneofthepetes@Function-NAS jellyfin]$ ./jellyfin.sh start
ln: /opt/jellyfin/jellyfin: File exists
error: failed to initialize display
[07:55:33] [INF] [1] Main: Jellyfin version: 10.10.3
[07:55:33] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /share/CACHEDEV1_DATA/.qpkg/jellyfin/logs]"]
[07:55:33] [INF] [1] Main: Arguments: ["/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin/bin/jellyfin.dll", "--datadir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/database", "--cachedir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache", "--webdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-web", "--configdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/conf", "--logdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/logs", "--ffmpeg=/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-ffmpeg/ffmpeg", "--package-name=pdulvp"]
[07:55:33] [INF] [1] Main: Operating system: QTS 5.2.2 (20241114)
[07:55:33] [INF] [1] Main: Architecture: X64
[07:55:33] [INF] [1] Main: 64-Bit Process: True
[07:55:33] [INF] [1] Main: User Interactive: True
[07:55:33] [INF] [1] Main: Processor count: 4
[07:55:33] [INF] [1] Main: Program data path: /share/CACHEDEV1_DATA/.qpkg/jellyfin/database
[07:55:33] [INF] [1] Main: Log directory path: /share/CACHEDEV1_DATA/.qpkg/jellyfin/logs
[07:55:33] [INF] [1] Main: Config directory path: /share/CACHEDEV1_DATA/.qpkg/jellyfin/conf
[07:55:33] [INF] [1] Main: Cache path: /share/CACHEDEV1_DATA/.qpkg/jellyfin/cache
[07:55:33] [INF] [1] Main: Temp directory path: /share/CACHEDEV1_DATA/.qpkg/jellyfin/cache/tmp/jellyfin
[07:55:33] [INF] [1] Main: Web resources path: /share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-web
[07:55:33] [INF] [1] Main: Application directory: /share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin/bin/
[07:55:34] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /share/CACHEDEV1_DATA/.qpkg/jellyfin/cache
[07:55:34] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[07:55:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Playback, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/DLNA_5.0.0.0/Jellyfin.Plugin.Dlna.Playback.dll
[07:55:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Model, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/DLNA_5.0.0.0/Jellyfin.Plugin.Dlna.Model.dll
[07:55:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Rssdp, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/DLNA_5.0.0.0/Rssdp.dll
[07:55:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/DLNA_5.0.0.0/Jellyfin.Plugin.Dlna.dll
[07:55:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.PlaybackReporting, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Playback Reporting_15.0.0.0/Jellyfin.Plugin.PlaybackReporting.dll
[07:55:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Playback Reporting_15.0.0.0/SQLitePCL.pretty.dll
[07:55:34] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.QnapConfiguration, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Jellyfin.Plugin.QnapConfiguration/Jellyfin.Plugin.QnapConfiguration.dll
[07:55:35] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly DocumentFormat.OpenXml, Version=2.16.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17 from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Reports_17.0.0.0/DocumentFormat.OpenXml.dll
[07:55:35] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly ExcelNumberFormat, Version=1.1.0.0, Culture=neutral, PublicKeyToken=23c6f5d73be07eca from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Reports_17.0.0.0/ExcelNumberFormat.dll
[07:55:35] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Reports_17.0.0.0/System.IO.Packaging.dll
[07:55:35] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly SixLabors.Fonts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13 from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Reports_17.0.0.0/SixLabors.Fonts.dll
[07:55:35] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly ClosedXML, Version=0.97.0.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Reports_17.0.0.0/ClosedXML.dll
[07:55:35] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Reports, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Reports_17.0.0.0/Jellyfin.Plugin.Reports.dll
[07:55:35] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.SessionCleaner, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Session Cleaner_4.0.0.0/Jellyfin.Plugin.SessionCleaner.dll
[07:55:36] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[07:55:36] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[07:55:36] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[07:55:36] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.29.0.1", "172.29.8.1", "172.29.12.1", "172.29.4.1", "10.0.5.1", "10.0.3.1", "10.0.7.1", "192.168.222.253"]
[07:55:36] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[07:55:36] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[07:55:36] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
Fontconfig error: Cannot load default config file
[07:55:40] [FTL] [1] Main: Error while starting server
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
   at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[07:55:40] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[07:55:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[07:55:41] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing PluginManager
`

**Comment by OutOfThisPlanet** [comment]
Rebuilt it. 
Watched stuff for a while, and went to sleep.

Woke up, and it is having issues (80mb single log file - I thought these got split up?). 


Restarted server, and.....

Nothing.

It never came back up again.

**Comment by OutOfThisPlanet** [comment]
So, after a bit of google searching, the above error could mean multiple instances of Jellyfin running. 

Hard to kill it when it keeps changing process...

![image](https://github.com/user-attachments/assets/a6ec23ff-33df-4520-ba64-0d3842aef72e)

**Comment by OutOfThisPlanet** [comment]
Will create a new issue for this.
