### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by OutOfThisPlanet** [pdulvp/jellyfin-qnap#122]
I have this issue (TS-253A, jellyfin).

Installed over the top of an existing jellyfin, and I can't connect. 
Logs (timestamps) seemed to show that the server was running in the background.

I uninstalled all of it, and recreated it from fresh.
Watched stuff for a while, and went to sleep.

Woke up, and it was having issues (80mb single log file - I thought these got split up?).
Restarted server, and.....

Nothing.
It never came back up again.

Starting the server manually in an SSH session with `./jellyfin.sh start`, and watched the logs:

`Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.`

So, after a bit of google searching, the above error could mean multiple instances of are Jellyfin running. 
Let's check the process list for jellyfin:

![image](https://github.com/user-attachments/assets/a6ec23ff-33df-4520-ba64-0d3842aef72e)

Oh, that's not good. It seems to be looping. Can't kill it if it keeps jumping processes like this!

The full log file after restart is:

`
[2024-12-14 16:58:32.466 +00:00] [INF] [1] Main: Jellyfin version: "10.10.3"
[2024-12-14 16:58:32.582 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /share/CACHEDEV1_DATA/.qpkg/jellyfin/logs]"]
[2024-12-14 16:58:32.591 +00:00] [INF] [1] Main: Arguments: ["/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin/bin/jellyfin.dll", "--datadir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/database", "--cachedir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache", "--webdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-web", "--configdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/conf", "--logdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/logs", "--ffmpeg=/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-ffmpeg/ffmpeg", "--package-name=pdulvp"]
[2024-12-14 16:58:32.592 +00:00] [INF] [1] Main: Operating system: "QTS 5.2.2 (20241114)"
[2024-12-14 16:58:32.593 +00:00] [INF] [1] Main: Architecture: X64
[2024-12-14 16:58:32.595 +00:00] [INF] [1] Main: 64-Bit Process: True
[2024-12-14 16:58:32.595 +00:00] [INF] [1] Main: User Interactive: True
[2024-12-14 16:58:32.595 +00:00] [INF] [1] Main: Processor count: 4
[2024-12-14 16:58:32.596 +00:00] [INF] [1] Main: Program data path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/database"
[2024-12-14 16:58:32.596 +00:00] [INF] [1] Main: Log directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/logs"
[2024-12-14 16:58:32.596 +00:00] [INF] [1] Main: Config directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/conf"
[2024-12-14 16:58:32.597 +00:00] [INF] [1] Main: Cache path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache"
[2024-12-14 16:58:32.598 +00:00] [INF] [1] Main: Temp directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache/tmp/jellyfin"
[2024-12-14 16:58:32.598 +00:00] [INF] [1] Main: Web resources path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-web"
[2024-12-14 16:58:32.599 +00:00] [INF] [1] Main: Application directory: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin/bin/"
[2024-12-14 16:58:33.339 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache"
[2024-12-14 16:58:33.677 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-12-14 16:58:33.755 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.QnapConfiguration, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null" from "/share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Jellyfin.Plugin.QnapConfiguration/Jellyfin.Plugin.QnapConfiguration.dll"
[2024-12-14 16:58:34.131 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-12-14 16:58:34.132 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-12-14 16:58:34.133 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-12-14 16:58:34.139 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.29.0.1", "172.29.8.1", "172.29.12.1", "172.29.4.1", "10.0.5.1", "10.0.3.1", "10.0.7.1", "192.168.222.253"]
[2024-12-14 16:58:34.142 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-12-14 16:58:34.143 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-12-14 16:58:34.144 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-12-14 16:58:38.430 +00:00] [FTL] [1] Main: Error while starting server
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
   at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
`

(I truncated the rest, as it seems to repeat).

**Comment by OutOfThisPlanet** [comment]
Strangely, as I was writing the above post, it came back online.

Now I want to know why!

Logs attached for completeness:

`[2024-12-14 16:58:32.466 +00:00] [INF] [1] Main: Jellyfin version: "10.10.3"
[2024-12-14 16:58:32.582 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /share/CACHEDEV1_DATA/.qpkg/jellyfin/logs]"]
[2024-12-14 16:58:32.591 +00:00] [INF] [1] Main: Arguments: ["/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin/bin/jellyfin.dll", "--datadir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/database", "--cachedir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache", "--webdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-web", "--configdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/conf", "--logdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/logs", "--ffmpeg=/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-ffmpeg/ffmpeg", "--package-name=pdulvp"]
[2024-12-14 16:58:32.592 +00:00] [INF] [1] Main: Operating system: "QTS 5.2.2 (20241114)"
[2024-12-14 16:58:32.593 +00:00] [INF] [1] Main: Architecture: X64
[2024-12-14 16:58:32.595 +00:00] [INF] [1] Main: 64-Bit Process: True
[2024-12-14 16:58:32.595 +00:00] [INF] [1] Main: User Interactive: True
[2024-12-14 16:58:32.595 +00:00] [INF] [1] Main: Processor count: 4
[2024-12-14 16:58:32.596 +00:00] [INF] [1] Main: Program data path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/database"
[2024-12-14 16:58:32.596 +00:00] [INF] [1] Main: Log directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/logs"
[2024-12-14 16:58:32.596 +00:00] [INF] [1] Main: Config directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/conf"
[2024-12-14 16:58:32.597 +00:00] [INF] [1] Main: Cache path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache"
[2024-12-14 16:58:32.598 +00:00] [INF] [1] Main: Temp directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache/tmp/jellyfin"
[2024-12-14 16:58:32.598 +00:00] [INF] [1] Main: Web resources path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-web"
[2024-12-14 16:58:32.599 +00:00] [INF] [1] Main: Application directory: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin/bin/"
[2024-12-14 16:58:33.339 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache"
[2024-12-14 16:58:33.677 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-12-14 16:58:33.755 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.QnapConfiguration, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null" from "/share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Jellyfin.Plugin.QnapConfiguration/Jellyfin.Plugin.QnapConfiguration.dll"
[2024-12-14 16:58:34.131 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-12-14 16:58:34.132 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-12-14 16:58:34.133 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-12-14 16:58:34.139 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.29.0.1", "172.29.8.1", "172.29.12.1", "172.29.4.1", "10.0.5.1", "10.0.3.1", "10.0.7.1", "192.168.222.253"]
[2024-12-14 16:58:34.142 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-12-14 16:58:34.143 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-12-14 16:58:34.144 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-12-14 16:58:38.430 +00:00] [FTL] [1] Main: Error while starting server
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Emby.Server.Implementations.Data.SqliteExtensions.Execute(SqliteConnection sqliteConnection, String commandText)
   at Emby.Server.Implementations.Data.ManagedConnection.Execute(String commandText)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.Initialize()
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize()
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2024-12-14 16:58:38.477 +00:00] [INF] [1] Main: Running query planner optimizations in the database... This might take a while
[2024-12-14 16:58:38.512 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
[2024-12-14 16:58:38.512 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "PluginManager"
[2024-12-14 17:16:18.945 +00:00] [INF] [1] Main: Jellyfin version: "10.10.3"
[2024-12-14 17:16:19.269 +00:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /share/CACHEDEV1_DATA/.qpkg/jellyfin/logs]"]
[2024-12-14 17:16:19.296 +00:00] [INF] [1] Main: Arguments: ["/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin/bin/jellyfin.dll", "--datadir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/database", "--cachedir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache", "--webdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-web", "--configdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/conf", "--logdir=/share/CACHEDEV1_DATA/.qpkg/jellyfin/logs", "--ffmpeg=/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-ffmpeg/ffmpeg", "--package-name=pdulvp"]
[2024-12-14 17:16:19.298 +00:00] [INF] [1] Main: Operating system: "QTS 5.2.2 (20241114)"
[2024-12-14 17:16:19.298 +00:00] [INF] [1] Main: Architecture: X64
[2024-12-14 17:16:19.303 +00:00] [INF] [1] Main: 64-Bit Process: True
[2024-12-14 17:16:19.303 +00:00] [INF] [1] Main: User Interactive: True
[2024-12-14 17:16:19.303 +00:00] [INF] [1] Main: Processor count: 4
[2024-12-14 17:16:19.305 +00:00] [INF] [1] Main: Program data path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/database"
[2024-12-14 17:16:19.305 +00:00] [INF] [1] Main: Log directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/logs"
[2024-12-14 17:16:19.305 +00:00] [INF] [1] Main: Config directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/conf"
[2024-12-14 17:16:19.307 +00:00] [INF] [1] Main: Cache path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache"
[2024-12-14 17:16:19.307 +00:00] [INF] [1] Main: Temp directory path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache/tmp/jellyfin"
[2024-12-14 17:16:19.310 +00:00] [INF] [1] Main: Web resources path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-web"
[2024-12-14 17:16:19.311 +00:00] [INF] [1] Main: Application directory: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin/bin/"
[2024-12-14 17:16:22.340 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache"
[2024-12-14 17:16:24.175 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-12-14 17:16:24.583 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.QnapConfiguration, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null" from "/share/CACHEDEV1_DATA/.qpkg/jellyfin/database/plugins/Jellyfin.Plugin.QnapConfiguration/Jellyfin.Plugin.QnapConfiguration.dll"
[2024-12-14 17:16:25.567 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-12-14 17:16:25.568 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-12-14 17:16:25.569 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-12-14 17:16:25.575 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "172.29.0.1", "172.29.8.1", "172.29.12.1", "172.29.4.1", "10.0.5.1", "10.0.3.1", "10.0.7.1", "192.168.222.253"]
[2024-12-14 17:16:25.577 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[2024-12-14 17:16:25.578 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-12-14 17:16:25.578 +00:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-12-14 17:20:36.885 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "QNAP.Configuration" "1.0.0.1"
[2024-12-14 17:20:36.889 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.10.3.0"
[2024-12-14 17:20:36.891 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.10.3.0"
[2024-12-14 17:20:36.892 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.10.3.0"
[2024-12-14 17:20:37.006 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.10.3.0"
[2024-12-14 17:20:37.007 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.10.3.0"
[2024-12-14 17:20:37.498 +00:00] [INF] [1] Main: Kestrel is listening on "0.0.0.0"
[2024-12-14 17:20:37.700 +00:00] [WRN] [1] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {9dec7e56-81ce-471c-bc4b-2426718f8b92} may be persisted to storage in unencrypted form.
[2024-12-14 17:20:41.618 +00:00] [WRN] [1] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The WebRootPath was not found: "/wwwroot". Static files may be unavailable.
[2024-12-14 17:20:42.339 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-12-14 17:20:42.436 +00:00] [INF] [15] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/share/CACHEDEV1_DATA/Media/Videos/TV"
[2024-12-14 17:20:42.443 +00:00] [INF] [20] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/share/CACHEDEV1_DATA/Media/Films"
[2024-12-14 17:20:42.461 +00:00] [INF] [19] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/share/CACHEDEV1_DATA/Media/Videos/Movies"
[2024-12-14 17:20:42.553 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Generate Trickplay Images" set to fire at 2024-12-15 03:00:00.000 +00:00, which is 09:39:17.4477677 from now.
[2024-12-14 17:20:42.677 +00:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-12-15 02:00:00.000 +00:00, which is 08:39:17.3220985 from now.
[2024-12-14 17:20:45.735 +00:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2024-12-14 17:20:46.048 +00:00] [INF] [15] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean Transcode Directory" Completed after 0 minute(s) and 0 seconds
[2024-12-14 17:20:46.211 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "7.0.2"
[2024-12-14 17:20:46.427 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "ac4", "dca", "flac", "mp3", "truehd"]
[2024-12-14 17:20:46.590 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-12-14 17:20:46.777 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["bwdif_cuda", "deinterlace_qsv", "deinterlace_vaapi", "flip_vulkan", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemapx", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "transpose_cuda", "transpose_opencl", "transpose_vaapi", "transpose_vulkan", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-12-14 17:20:47.455 +00:00] [INF] [19] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2024-12-14 17:20:48.068 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2024-12-14 17:20:50.082 +00:00] [INF] [21] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/share/CACHEDEV1_DATA/Media/TV"
[2024-12-14 17:21:05.157 +00:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "/share/CACHEDEV1_DATA/.qpkg/jellyfin/jellyfin-ffmpeg/ffmpeg"
[2024-12-14 17:21:05.182 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "9c3cb9f5510a4a1e8349303cb8f9abed"
[2024-12-14 17:21:05.183 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-12-14 17:21:05.183 +00:00] [INF] [1] Main: Startup complete 0:04:48.5250744
[2024-12-14 17:21:41.771 +00:00] [INF] [22] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/share/CACHEDEV1_DATA/Media/Music"
[2024-12-14 17:31:46.450 +00:00] [INF] [30] Jellyfin.Drawing.ImageProcessor: Creating image collage and saving to "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache/tmp/jellyfin/ff3c19c73dc94ee196b83c9eb366164c.png"
[2024-12-14 17:31:47.527 +00:00] [INF] [30] Jellyfin.Drawing.ImageProcessor: Completed creation of image collage and saved to "/share/CACHEDEV1_DATA/.qpkg/jellyfin/cache/tmp/jellyfin/ff3c19c73dc94ee196b83c9eb366164c.png"`

**Comment by OutOfThisPlanet** [comment]
Since it is currently working, I will close this issue.

Further info was also posted in this issue (before I opened this one) : https://github.com/pdulvp/jellyfin-qnap/issues/121#issuecomment-2542824925
