### ISSUE TITLE
Enable System Globalization

### ISSUE THREAD

**Issue by pdulvp** [pdulvp/jellyfin-qnap#13]
System.Globalization.Invariant has been enabled otherwise jellyfin doesn't launch.
https://github.com/pdulvp/jellyfin-qnap/blob/master/jellyfin-server.sh#L38-L42

This is probably why it seems impossible to change the UI language of jellyfin.

```
[/share/CACHEDEV1_DATA/.qpkg/jellyfin] # ./jellyfin.sh start
ln: /opt/jellyfin/jellyfin: File exists
libva info: VA-API version 1.15.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_15
libva error: /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_15
libva info: va_openDriver() returns 0
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser+<>c.<.cctor>b__20_0()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(System.Threading.LazyThreadSafetyMode)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(System.LazyHelper, Boolean)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at CommandLine.Parser.get_Default()
   at Jellyfin.Server.Program.Main(System.String[])
   at Jellyfin.Server.Program.<Main>(System.String[])
./jellyfin.sh: line 10: 16563 Aborted                 $QPKG_ROOT/jellyfin/bin/jellyfin --datadir=$QPKG_ROOT/database --cachedir=$QPKG_ROOT/cache --webdir=$QPKG_ROOT/jellyfin-web --configdir=$QPKG_ROOT/conf --logdir=$QPKG_ROOT/logs --ffmpeg=$QPKG_ROOT/jellyfin-ffmpeg/ffmpeg --restartpath=/etc/init.d/jellyfin.sh --restartargs=restart --package-name=pdulvp
```

https://docs.microsoft.com/en-us/dotnet/core/runtime-config/globalization

**Comment by pdulvp** [comment]
Seems to work without any changes
