### ISSUE TITLE
Error in "ffprobe"

### ISSUE THREAD

**Issue by ZeVince** [pdulvp/jellyfin-qnap#14]
=> 10.8.0-beta3 Pre-release Version based on: jellyfin-server_10.8.0-beta3 jellyfin-web_10.8.0-beta3
**AND** 10.8.0-beta1 jellyfin-ffmpeg_4.4.1-4

- Probe new media OK

=> 10.8.0-beta3 Pre-release Version based on: jellyfin-server_10.8.0-beta3 jellyfin-web_10.8.0-beta3 jellyfin-ffmpeg5_5.0.1-4

- Failed to probe new media

[jellyfin-ffmpeg]$ ./ffprobe
LIBVA_DRIVER_NAME_JELLYFIN=iHD
ffprobe version 5.0.1-Jellyfin Copyright (c) 2007-2022 the FFmpeg developers

[2022-05-19 18:08:45.157 +02:00] [ERR] [71] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: 'L' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'L' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---

=> 10.8.0-beta3 Pre-release Version based on: jellyfin-server_10.8.0-beta3 jellyfin-web_10.8.0-beta3 jellyfin-ffmpeg_4.4.1-4

- Failed to probe new media
   
[jellyfin-ffmpeg]$ ./ffprobe
LIBVA_DRIVER_NAME_JELLYFIN=iHD
ffprobe version 4.4.1-Jellyfin Copyright (c) 2007-2021 the FFmpeg developers

 [2022-05-19 18:20:37.103 +02:00] [ERR] [30] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: 'L' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'L' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

**Comment by pdulvp** [comment]
Looks similar error msg than https://github.com/jellyfin/jellyfin/issues/7754. related?

**Comment by pdulvp** [comment]
@ZeVince if you open `Administration > Dashboard > Advanced > Logs`
vainfo log is telling that you have the iHD ? or is it the i965 (like mine) ?

```
vainfo2: VA-API version: 1.15 (libva 2.15.0.pre1)
vainfo2: Driver version: Intel **i965** driver for Intel(R) CherryView - 2.4.0.pre1 ()
vainfo2: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
```

If it is telling i965, can you try by setting 
`Administration > Dashboard > Advanced > Plugins > Qnap.Configuration > VAAPI driver` to i965

**Comment by pdulvp** [comment]
For the issue, it seems fixed on my side with 10.8.1-1. Can you try with the last release if it reproduce?
@MoFanFr @ZeVince

Ensure that you have the [video-acceleration](https://github.com/pdulvp/jellyfin-qnap#-enable-video-acceleration-in-jellyfin-) configured in settings / try several configurations within it.
Please let us know.

**Comment by ZeVince** [comment]
Unfortunately the issue is still here with [10.8.1-1](https://github.com/pdulvp/jellyfin-qnap/releases/tag/10811.10811.5017_c17ecb9f)

New media is not scanned when added because of :
[2022-07-06 10:38:40.128 +02:00] [ERR] [34] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: 'L' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

Normal output :
![Screenshot 2022-07-06 112043](https://user-images.githubusercontent.com/48491925/177523008-0afdc397-ed5c-4811-b3a8-c2af77352eb6.png)

Current output :
![Screenshot 2022-07-06 112123](https://user-images.githubusercontent.com/48491925/177523068-88316590-8897-425e-8f02-dcdc4fb59b00.png)

For reference:
vainfo2: VA-API version: 1.15 (libva 2.15.0.pre1)
vainfo2: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.3 (74f40ee)
vainfo2: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats

**Comment by MoFanFr** [comment]
I have uninstalled and reinstalled Jellyfin and I still have the same problem:

[2022-07-06 19:50:57.331 +08:00] [ERR] [51] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe"
System.Text.Json.JsonException: 'L' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

I have tried different configurations of the hardware acceleration but no improvement.

**Comment by freedomcatjin** [comment]
> Unfortunately the issue is still here with [10.8.1-1](https://github.com/pdulvp/jellyfin-qnap/releases/tag/10811.10811.5017_c17ecb9f)
> 
> New media is not scanned when added because of : [2022-07-06 10:38:40.128 +02:00] [ERR] [34] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "ffprobe" System.Text.Json.JsonException: 'L' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
> 
> Normal output : ![Screenshot 2022-07-06 112043](https://user-images.githubusercontent.com/48491925/177523008-0afdc397-ed5c-4811-b3a8-c2af77352eb6.png)
> 
> Current output : ![Screenshot 2022-07-06 112123](https://user-images.githubusercontent.com/48491925/177523068-88316590-8897-425e-8f02-dcdc4fb59b00.png)
> 
> Thus, back to using the lastest working ffmepg :
> 
> ffmpeg version 4.4.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers built with gcc 10 (Debian 10.2.1-6)
> 
> ![Screenshot 2022-07-06 154739](https://user-images.githubusercontent.com/48491925/177566070-51a4dd4d-eca1-431a-a6b5-c2ac02451cfb.png)
> 
> For reference: vainfo2: VA-API version: 1.15 (libva 2.15.0.pre1) vainfo2: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.3 (74f40ee) vainfo2: Supported profile and entrypoints VAProfileNone : VAEntrypointVideoProc VAProfileNone : VAEntrypointStats

这个问题其实就使用硬件时的解码器问题，不要使用jellyfin内置的ffmpeg，需要安装另外的解码器Mutlimedia Tools，使用这个解码器的ffmpeg，就不会有这个报错了

**Comment by pdulvp** [comment]
Shall be fixed now
